// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package job

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Requestjob struct {
	Jobid                int64    `protobuf:"varint,1,opt,name=jobid,proto3" json:"jobid,omitempty"`
	Jobname              string   `protobuf:"bytes,2,opt,name=jobname,proto3" json:"jobname,omitempty"`
	Submiter             string   `protobuf:"bytes,3,opt,name=submiter,proto3" json:"submiter,omitempty"`
	Starttime            int64    `protobuf:"varint,4,opt,name=starttime,proto3" json:"starttime,omitempty"`
	Endtime              int64    `protobuf:"varint,5,opt,name=endtime,proto3" json:"endtime,omitempty"`
	Qtime                int64    `protobuf:"varint,6,opt,name=qtime,proto3" json:"qtime,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Nodes                []string `protobuf:"bytes,8,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Cpus                 []int64  `protobuf:"varint,9,rep,packed,name=cpus,proto3" json:"cpus,omitempty"`
	Gpus                 []int64  `protobuf:"varint,10,rep,packed,name=gpus,proto3" json:"gpus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Requestjob) Reset()         { *m = Requestjob{} }
func (m *Requestjob) String() string { return proto.CompactTextString(m) }
func (*Requestjob) ProtoMessage()    {}
func (*Requestjob) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_95bd8b4816f176dd, []int{0}
}
func (m *Requestjob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requestjob.Unmarshal(m, b)
}
func (m *Requestjob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requestjob.Marshal(b, m, deterministic)
}
func (dst *Requestjob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requestjob.Merge(dst, src)
}
func (m *Requestjob) XXX_Size() int {
	return xxx_messageInfo_Requestjob.Size(m)
}
func (m *Requestjob) XXX_DiscardUnknown() {
	xxx_messageInfo_Requestjob.DiscardUnknown(m)
}

var xxx_messageInfo_Requestjob proto.InternalMessageInfo

func (m *Requestjob) GetJobid() int64 {
	if m != nil {
		return m.Jobid
	}
	return 0
}

func (m *Requestjob) GetJobname() string {
	if m != nil {
		return m.Jobname
	}
	return ""
}

func (m *Requestjob) GetSubmiter() string {
	if m != nil {
		return m.Submiter
	}
	return ""
}

func (m *Requestjob) GetStarttime() int64 {
	if m != nil {
		return m.Starttime
	}
	return 0
}

func (m *Requestjob) GetEndtime() int64 {
	if m != nil {
		return m.Endtime
	}
	return 0
}

func (m *Requestjob) GetQtime() int64 {
	if m != nil {
		return m.Qtime
	}
	return 0
}

func (m *Requestjob) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Requestjob) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Requestjob) GetCpus() []int64 {
	if m != nil {
		return m.Cpus
	}
	return nil
}

func (m *Requestjob) GetGpus() []int64 {
	if m != nil {
		return m.Gpus
	}
	return nil
}

type Responsejob struct {
	Status               int64    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Responsejob) Reset()         { *m = Responsejob{} }
func (m *Responsejob) String() string { return proto.CompactTextString(m) }
func (*Responsejob) ProtoMessage()    {}
func (*Responsejob) Descriptor() ([]byte, []int) {
	return fileDescriptor_job_95bd8b4816f176dd, []int{1}
}
func (m *Responsejob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Responsejob.Unmarshal(m, b)
}
func (m *Responsejob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Responsejob.Marshal(b, m, deterministic)
}
func (dst *Responsejob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Responsejob.Merge(dst, src)
}
func (m *Responsejob) XXX_Size() int {
	return xxx_messageInfo_Responsejob.Size(m)
}
func (m *Responsejob) XXX_DiscardUnknown() {
	xxx_messageInfo_Responsejob.DiscardUnknown(m)
}

var xxx_messageInfo_Responsejob proto.InternalMessageInfo

func (m *Responsejob) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*Requestjob)(nil), "job.Requestjob")
	proto.RegisterType((*Responsejob)(nil), "job.Responsejob")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobClient is the client API for Job service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobClient interface {
	UpdateAndCreateJob(ctx context.Context, in *Requestjob, opts ...grpc.CallOption) (*Responsejob, error)
}

type jobClient struct {
	cc *grpc.ClientConn
}

func NewJobClient(cc *grpc.ClientConn) JobClient {
	return &jobClient{cc}
}

func (c *jobClient) UpdateAndCreateJob(ctx context.Context, in *Requestjob, opts ...grpc.CallOption) (*Responsejob, error) {
	out := new(Responsejob)
	err := c.cc.Invoke(ctx, "/job.Job/UpdateAndCreateJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServer is the server API for Job service.
type JobServer interface {
	UpdateAndCreateJob(context.Context, *Requestjob) (*Responsejob, error)
}

func RegisterJobServer(s *grpc.Server, srv JobServer) {
	s.RegisterService(&_Job_serviceDesc, srv)
}

func _Job_UpdateAndCreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Requestjob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).UpdateAndCreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.Job/UpdateAndCreateJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).UpdateAndCreateJob(ctx, req.(*Requestjob))
	}
	return interceptor(ctx, in, info, handler)
}

var _Job_serviceDesc = grpc.ServiceDesc{
	ServiceName: "job.Job",
	HandlerType: (*JobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateAndCreateJob",
			Handler:    _Job_UpdateAndCreateJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job.proto",
}

func init() { proto.RegisterFile("job.proto", fileDescriptor_job_95bd8b4816f176dd) }

var fileDescriptor_job_95bd8b4816f176dd = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0x87, 0xad, 0xd9, 0xed, 0x6e, 0xc7, 0x83, 0x32, 0x88, 0x84, 0xc5, 0x43, 0x29, 0x08, 0x3d,
	0xed, 0x41, 0x4f, 0xde, 0x14, 0x6f, 0x1e, 0x03, 0x3e, 0x40, 0x63, 0x07, 0x69, 0xa1, 0x99, 0x6e,
	0x33, 0x7d, 0x7b, 0x0f, 0x4b, 0x92, 0xee, 0xf6, 0x96, 0xef, 0x9b, 0x30, 0x7f, 0x7e, 0x50, 0xf4,
	0x6c, 0x8f, 0xe3, 0xc4, 0xc2, 0xa8, 0x7a, 0xb6, 0xd5, 0x7f, 0x06, 0x60, 0xe8, 0x34, 0x93, 0x97,
	0x9e, 0x2d, 0x3e, 0xc2, 0xb6, 0x67, 0xdb, 0xb5, 0x3a, 0x2b, 0xb3, 0x5a, 0x99, 0x04, 0xa8, 0x61,
	0xd7, 0xb3, 0x75, 0xcd, 0x40, 0xfa, 0xb6, 0xcc, 0xea, 0xc2, 0x5c, 0x10, 0x0f, 0xb0, 0xf7, 0xb3,
	0x1d, 0x3a, 0xa1, 0x49, 0xab, 0x58, 0xba, 0x32, 0x3e, 0x43, 0xe1, 0xa5, 0x99, 0x44, 0xba, 0x81,
	0xf4, 0x26, 0xf6, 0x5b, 0x45, 0xe8, 0x49, 0xae, 0x8d, 0xb5, 0x6d, 0xac, 0x5d, 0x30, 0xec, 0x70,
	0x8a, 0x3e, 0x4f, 0x3b, 0x44, 0xc0, 0x27, 0xc8, 0xbd, 0x34, 0x32, 0x7b, 0xbd, 0x8b, 0x73, 0x16,
	0x0a, 0xbf, 0x1d, 0xb7, 0xe4, 0xf5, 0xbe, 0x54, 0x75, 0x61, 0x12, 0x20, 0xc2, 0xe6, 0x77, 0x9c,
	0xbd, 0x2e, 0x4a, 0x55, 0x2b, 0x13, 0xdf, 0xc1, 0xfd, 0x05, 0x07, 0xc9, 0x85, 0x77, 0xf5, 0x02,
	0x77, 0x86, 0xfc, 0xc8, 0xce, 0x53, 0x38, 0x7f, 0x1d, 0x92, 0xee, 0x5f, 0xe8, 0xf5, 0x03, 0xd4,
	0x37, 0x5b, 0x7c, 0x07, 0xfc, 0x19, 0xdb, 0x46, 0xe8, 0xd3, 0xb5, 0x5f, 0x13, 0x35, 0x42, 0xc1,
	0xde, 0x1f, 0x43, 0xa6, 0x6b, 0x88, 0x87, 0x87, 0x45, 0x5c, 0xfb, 0x56, 0x37, 0x36, 0x8f, 0x99,
	0xbf, 0x9d, 0x03, 0x00, 0x00, 0xff, 0xff, 0x08, 0x3b, 0x5e, 0xbe, 0x80, 0x01, 0x00, 0x00,
}
