// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jobsearch.proto

package jobsearch

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Requestjob struct {
	User                 []string `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	Status               []string `protobuf:"bytes,2,rep,name=status,proto3" json:"status,omitempty"`
	Starttime            int64    `protobuf:"varint,3,opt,name=starttime,proto3" json:"starttime,omitempty"`
	Endtime              int64    `protobuf:"varint,4,opt,name=endtime,proto3" json:"endtime,omitempty"`
	Qtime                int64    `protobuf:"varint,5,opt,name=qtime,proto3" json:"qtime,omitempty"`
	Jobname              string   `protobuf:"bytes,6,opt,name=jobname,proto3" json:"jobname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Requestjob) Reset()         { *m = Requestjob{} }
func (m *Requestjob) String() string { return proto.CompactTextString(m) }
func (*Requestjob) ProtoMessage()    {}
func (*Requestjob) Descriptor() ([]byte, []int) {
	return fileDescriptor_jobsearch_35e610fe824284da, []int{0}
}
func (m *Requestjob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requestjob.Unmarshal(m, b)
}
func (m *Requestjob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requestjob.Marshal(b, m, deterministic)
}
func (dst *Requestjob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requestjob.Merge(dst, src)
}
func (m *Requestjob) XXX_Size() int {
	return xxx_messageInfo_Requestjob.Size(m)
}
func (m *Requestjob) XXX_DiscardUnknown() {
	xxx_messageInfo_Requestjob.DiscardUnknown(m)
}

var xxx_messageInfo_Requestjob proto.InternalMessageInfo

func (m *Requestjob) GetUser() []string {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Requestjob) GetStatus() []string {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *Requestjob) GetStarttime() int64 {
	if m != nil {
		return m.Starttime
	}
	return 0
}

func (m *Requestjob) GetEndtime() int64 {
	if m != nil {
		return m.Endtime
	}
	return 0
}

func (m *Requestjob) GetQtime() int64 {
	if m != nil {
		return m.Qtime
	}
	return 0
}

func (m *Requestjob) GetJobname() string {
	if m != nil {
		return m.Jobname
	}
	return ""
}

type Jobitem struct {
	Jobid                int64    `protobuf:"varint,1,opt,name=jobid,proto3" json:"jobid,omitempty"`
	Jobname              string   `protobuf:"bytes,2,opt,name=jobname,proto3" json:"jobname,omitempty"`
	Submiter             string   `protobuf:"bytes,3,opt,name=submiter,proto3" json:"submiter,omitempty"`
	Starttime            int64    `protobuf:"varint,4,opt,name=starttime,proto3" json:"starttime,omitempty"`
	Endtime              int64    `protobuf:"varint,5,opt,name=endtime,proto3" json:"endtime,omitempty"`
	Qtime                int64    `protobuf:"varint,6,opt,name=qtime,proto3" json:"qtime,omitempty"`
	Status               string   `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Nodes                []string `protobuf:"bytes,8,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Cpus                 []int64  `protobuf:"varint,9,rep,packed,name=cpus,proto3" json:"cpus,omitempty"`
	Gpus                 []int64  `protobuf:"varint,10,rep,packed,name=gpus,proto3" json:"gpus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Jobitem) Reset()         { *m = Jobitem{} }
func (m *Jobitem) String() string { return proto.CompactTextString(m) }
func (*Jobitem) ProtoMessage()    {}
func (*Jobitem) Descriptor() ([]byte, []int) {
	return fileDescriptor_jobsearch_35e610fe824284da, []int{1}
}
func (m *Jobitem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jobitem.Unmarshal(m, b)
}
func (m *Jobitem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jobitem.Marshal(b, m, deterministic)
}
func (dst *Jobitem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jobitem.Merge(dst, src)
}
func (m *Jobitem) XXX_Size() int {
	return xxx_messageInfo_Jobitem.Size(m)
}
func (m *Jobitem) XXX_DiscardUnknown() {
	xxx_messageInfo_Jobitem.DiscardUnknown(m)
}

var xxx_messageInfo_Jobitem proto.InternalMessageInfo

func (m *Jobitem) GetJobid() int64 {
	if m != nil {
		return m.Jobid
	}
	return 0
}

func (m *Jobitem) GetJobname() string {
	if m != nil {
		return m.Jobname
	}
	return ""
}

func (m *Jobitem) GetSubmiter() string {
	if m != nil {
		return m.Submiter
	}
	return ""
}

func (m *Jobitem) GetStarttime() int64 {
	if m != nil {
		return m.Starttime
	}
	return 0
}

func (m *Jobitem) GetEndtime() int64 {
	if m != nil {
		return m.Endtime
	}
	return 0
}

func (m *Jobitem) GetQtime() int64 {
	if m != nil {
		return m.Qtime
	}
	return 0
}

func (m *Jobitem) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Jobitem) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *Jobitem) GetCpus() []int64 {
	if m != nil {
		return m.Cpus
	}
	return nil
}

func (m *Jobitem) GetGpus() []int64 {
	if m != nil {
		return m.Gpus
	}
	return nil
}

type Responsejob struct {
	Jobs                 []*Jobitem `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Responsejob) Reset()         { *m = Responsejob{} }
func (m *Responsejob) String() string { return proto.CompactTextString(m) }
func (*Responsejob) ProtoMessage()    {}
func (*Responsejob) Descriptor() ([]byte, []int) {
	return fileDescriptor_jobsearch_35e610fe824284da, []int{2}
}
func (m *Responsejob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Responsejob.Unmarshal(m, b)
}
func (m *Responsejob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Responsejob.Marshal(b, m, deterministic)
}
func (dst *Responsejob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Responsejob.Merge(dst, src)
}
func (m *Responsejob) XXX_Size() int {
	return xxx_messageInfo_Responsejob.Size(m)
}
func (m *Responsejob) XXX_DiscardUnknown() {
	xxx_messageInfo_Responsejob.DiscardUnknown(m)
}

var xxx_messageInfo_Responsejob proto.InternalMessageInfo

func (m *Responsejob) GetJobs() []*Jobitem {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func init() {
	proto.RegisterType((*Requestjob)(nil), "job.Requestjob")
	proto.RegisterType((*Jobitem)(nil), "job.Jobitem")
	proto.RegisterType((*Responsejob)(nil), "job.Responsejob")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JobClient is the client API for Job service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JobClient interface {
	FindJob(ctx context.Context, in *Requestjob, opts ...grpc.CallOption) (*Responsejob, error)
}

type jobClient struct {
	cc *grpc.ClientConn
}

func NewJobClient(cc *grpc.ClientConn) JobClient {
	return &jobClient{cc}
}

func (c *jobClient) FindJob(ctx context.Context, in *Requestjob, opts ...grpc.CallOption) (*Responsejob, error) {
	out := new(Responsejob)
	err := c.cc.Invoke(ctx, "/job.Job/FindJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JobServer is the server API for Job service.
type JobServer interface {
	FindJob(context.Context, *Requestjob) (*Responsejob, error)
}

func RegisterJobServer(s *grpc.Server, srv JobServer) {
	s.RegisterService(&_Job_serviceDesc, srv)
}

func _Job_FindJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Requestjob)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobServer).FindJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/job.Job/FindJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobServer).FindJob(ctx, req.(*Requestjob))
	}
	return interceptor(ctx, in, info, handler)
}

var _Job_serviceDesc = grpc.ServiceDesc{
	ServiceName: "job.Job",
	HandlerType: (*JobServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindJob",
			Handler:    _Job_FindJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jobsearch.proto",
}

func init() { proto.RegisterFile("jobsearch.proto", fileDescriptor_jobsearch_35e610fe824284da) }

var fileDescriptor_jobsearch_35e610fe824284da = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x6e, 0x83, 0x30,
	0x0c, 0xc6, 0x47, 0xc3, 0x9f, 0xe2, 0x4e, 0xea, 0x14, 0x55, 0x53, 0x54, 0xed, 0x80, 0x38, 0x71,
	0x62, 0x52, 0xa7, 0xbd, 0xc2, 0x0e, 0x3d, 0xe6, 0x0d, 0x48, 0xb1, 0x36, 0x90, 0xc0, 0x2d, 0x09,
	0xef, 0xb3, 0xd7, 0xdc, 0x6d, 0x8a, 0x69, 0x4b, 0x7b, 0xd8, 0x6e, 0xfe, 0x7e, 0xb6, 0xe1, 0xd3,
	0xe7, 0xc0, 0xba, 0x25, 0x63, 0xb1, 0x1a, 0x0e, 0x5f, 0xe5, 0x71, 0x20, 0x47, 0x52, 0xb4, 0x64,
	0xf2, 0xef, 0x00, 0x40, 0xe3, 0x69, 0x44, 0xeb, 0x5a, 0x32, 0x52, 0x42, 0x38, 0x5a, 0x1c, 0x54,
	0x90, 0x89, 0x22, 0xd5, 0x5c, 0xcb, 0x67, 0x88, 0xad, 0xab, 0xdc, 0x68, 0xd5, 0x82, 0xe9, 0x59,
	0xc9, 0x17, 0x48, 0xad, 0xab, 0x06, 0xe7, 0x9a, 0x0e, 0x95, 0xc8, 0x82, 0x42, 0xe8, 0x19, 0x48,
	0x05, 0x09, 0xf6, 0x35, 0xf7, 0x42, 0xee, 0x5d, 0xa4, 0xdc, 0x40, 0x74, 0x62, 0x1e, 0x31, 0x9f,
	0x84, 0x9f, 0x6f, 0xc9, 0xf4, 0x55, 0x87, 0x2a, 0xce, 0x82, 0x22, 0xd5, 0x17, 0x99, 0xff, 0x04,
	0x90, 0xec, 0xc9, 0x34, 0x0e, 0x3b, 0xbf, 0xdb, 0x92, 0x69, 0x6a, 0x15, 0x4c, 0xbb, 0x2c, 0x6e,
	0x77, 0x17, 0x77, 0xbb, 0x72, 0x0b, 0x4b, 0x3b, 0x9a, 0xae, 0x71, 0x38, 0xb0, 0xc5, 0x54, 0x5f,
	0xf5, 0xbd, 0xff, 0xf0, 0x1f, 0xff, 0xd1, 0x1f, 0xfe, 0xe3, 0x5b, 0xff, 0x73, 0x4a, 0x09, 0xff,
	0xe7, 0x92, 0xd2, 0x06, 0xa2, 0x9e, 0x6a, 0xb4, 0x6a, 0xc9, 0xe1, 0x4d, 0xc2, 0xe7, 0x7c, 0x38,
	0x8e, 0x56, 0xa5, 0x99, 0x28, 0x84, 0xe6, 0xda, 0xb3, 0x4f, 0xcf, 0x60, 0x62, 0xbe, 0xce, 0x5f,
	0x61, 0xa5, 0xd1, 0x1e, 0xa9, 0xb7, 0xe8, 0xcf, 0x93, 0x41, 0xe8, 0xaf, 0xc8, 0xe7, 0x59, 0xed,
	0x1e, 0xcb, 0x96, 0x4c, 0x79, 0x8e, 0x46, 0x73, 0x67, 0xf7, 0x0e, 0x62, 0x4f, 0x46, 0x96, 0x90,
	0x7c, 0x34, 0x7d, 0xed, 0xcb, 0x35, 0x4f, 0xcd, 0x37, 0xde, 0x3e, 0x9d, 0xc1, 0xf5, 0xb3, 0xf9,
	0x83, 0x89, 0xf9, 0x49, 0xbc, 0xfd, 0x06, 0x00, 0x00, 0xff, 0xff, 0x89, 0xd1, 0xa9, 0x78, 0x25,
	0x02, 0x00, 0x00,
}
